# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 46958e5ff1fd4225e1e71fb96b05bee59e8c3158e5577b28d3f84470de8803cc336088d2add2af61ba51e32e922e56db4b1d0e698c4c9c258c5f77d2eab2ed00

test:
  secret_key_base: 0e4b3e4bb1be3889ef9fb1f97f68e6f836cd9a23e4379775edd1053d806139d05984923e82e4497ea7d2216e85c6576f2a11d1b4b4e4220c88bc3961bb5e2cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= begin IO.read("/home/zhuwu/.secret_key_base") rescue "" end %>
