development: &development
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_development

test: &test
  adapter: mysql2
  host: localhost
  username: root
  password:
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_test

production: &production
  adapter: mysql2
  host: localhost
  database: <%= Rails.application.engine_name.gsub(/_application/,'').downcase %>_production
  username: blog
  password: <%= begin IO.read("/home/zhuwu/.blog_db_secret") rescue "" end %>
